Repository personull-mfc/mfc-coordinating, pull requests merged in 2024-05, with the labels that each got.

#2 [FEATURE] #1 레포지토리 초기세팅
  src/main/java/com/mfc/coordinating/common/entity/BaseEntity.java
  src/main/java/com/mfc/coordinating/common/exception/BaseException.java
  src/main/java/com/mfc/coordinating/common/exception/BaseExceptionHandler.java
  src/main/java/com/mfc/coordinating/common/response/BaseResponse.java
  src/main/java/com/mfc/coordinating/common/response/BaseResponseStatus.java
Labels: 💫 feature, 🌓Backend

#4 [FEATURE] 코디네이팅 엔티티 작성
  src/main/java/com/mfc/coordinating/confirms/application/ConfirmsService.java
  src/main/java/com/mfc/coordinating/confirms/application/ConfirmsServiceImpl.java
  src/main/java/com/mfc/coordinating/confirms/domain/Confirms.java
  src/main/java/com/mfc/coordinating/confirms/infrastructure/ConfirmsRepository.java
  src/main/java/com/mfc/coordinating/confirms/presentation/ConfirmsController.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsService.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/domain/Requests.java
  src/main/java/com/mfc/coordinating/requests/enums/ReviewStates.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestsRepository.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
  src/main/java/com/mfc/coordinating/reviews/application/ReviewsService.java
  src/main/java/com/mfc/coordinating/reviews/application/ReviewsServiceImpl.java
  src/main/java/com/mfc/coordinating/reviews/entity/Reviews.java
  src/main/java/com/mfc/coordinating/reviews/infrastructure/ReviewsRepository.java
  src/main/java/com/mfc/coordinating/reviews/presentation/ReviewsController.java
  src/main/java/com/mfc/coordinating/submissions/application/SubmissionsService.java
  src/main/java/com/mfc/coordinating/submissions/application/SubmissionsServiceImpl.java
  src/main/java/com/mfc/coordinating/submissions/entity/Submissions.java
  src/main/java/com/mfc/coordinating/submissions/infrastructure/SubmissionsRepository.java
  src/main/java/com/mfc/coordinating/submissions/presentation/SubmissionsController.java
Labels: 💫 feature, 🌓Backend

#6 [FEATURE] 코디 요청서 API 작성
  .gitignore
  build.gradle
  src/main/java/com/mfc/coordinating/CoordinatingApplication.java
  src/main/java/com/mfc/coordinating/common/entity/BaseEntity.java
  src/main/java/com/mfc/coordinating/common/response/BaseResponseStatus.java
  src/main/java/com/mfc/coordinating/config/ModelMapperConfig.java
  src/main/java/com/mfc/coordinating/config/SwaggerConfig.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsService.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/domain/Requests.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsCreateReqDto.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsUpdateReqDto.java
  src/main/java/com/mfc/coordinating/requests/dto/res/RequestsDetailResDto.java
  src/main/java/com/mfc/coordinating/requests/dto/res/RequestsListResDto.java
  src/main/java/com/mfc/coordinating/requests/enums/RequestsListSortType.java
  src/main/java/com/mfc/coordinating/requests/enums/RequestsStates.java
  src/main/java/com/mfc/coordinating/requests/enums/ReviewStates.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestsRepository.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
  src/main/java/com/mfc/coordinating/requests/vo/req/RequestsCreateReqVo.java
  src/main/java/com/mfc/coordinating/requests/vo/req/RequestsUpdateReqVo.java
  src/main/java/com/mfc/coordinating/requests/vo/res/RequestsDetailResVo.java
Labels: 💫 feature, 🌓Backend

#8 [FEATURE] 코디 요청 관련 회원, 파트너 API 작업
  src/main/java/com/mfc/coordinating/common/exception/BaseExceptionHandler.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsService.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/domain/Requests.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsCreateReqDto.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsUpdateReqDto.java
  src/main/java/com/mfc/coordinating/requests/dto/res/RequestsDetailResDto.java
  src/main/java/com/mfc/coordinating/requests/enums/RequestsStates.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestsRepository.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
  src/main/java/com/mfc/coordinating/requests/vo/req/RequestsCreateReqVo.java
  src/main/java/com/mfc/coordinating/requests/vo/req/RequestsUpdateReqVo.java
  src/main/java/com/mfc/coordinating/requests/vo/res/RequestsDetailResVo.java
Labels: 💫 feature, ♻️ refactor, 🌓Backend

#13 코디네이팅 CRUD 구현
  .github/ISSUE_TEMPLATE/default-template.md
  .github/pull_request_template.md
  src/main/java/com/mfc/coordinating/common/response/BaseResponseStatus.java
  src/main/java/com/mfc/coordinating/confirms/domain/Confirms.java
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesService.java
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesServiceImpl.java
  src/main/java/com/mfc/coordinating/coordinates/domain/Coordinates.java
  src/main/java/com/mfc/coordinating/coordinates/domain/CoordinatesImage.java
  src/main/java/com/mfc/coordinating/coordinates/dto/request/CoordinatesRequest.java
  src/main/java/com/mfc/coordinating/coordinates/dto/response/CoordinatesResponse.java
  src/main/java/com/mfc/coordinating/coordinates/infrastructure/CoordinatesImageRepository.java
  src/main/java/com/mfc/coordinating/coordinates/infrastructure/CoordinatesRepository.java
  src/main/java/com/mfc/coordinating/coordinates/presentation/CoordinatesController.java
  src/main/java/com/mfc/coordinating/reviews/presentation/ReviewsController.java
Labels: 💫 feature, 🌓Backend

#15 [CHORE] 배포 관련 설정 추가
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/mfc/coordinating/CoordinatingApplication.java
  src/main/java/com/mfc/coordinating/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: ⚙️ chore, 🗃 infra, 🌓Backend

#17 확정 제안서 CRUD 개발
  build.gradle
  src/main/java/com/mfc/coordinating/common/response/BaseResponseStatus.java
  src/main/java/com/mfc/coordinating/confirms/application/ConfirmsService.java
  src/main/java/com/mfc/coordinating/confirms/application/ConfirmsServiceImpl.java
  src/main/java/com/mfc/coordinating/confirms/domain/Confirms.java
  src/main/java/com/mfc/coordinating/confirms/dto/request/ConfirmsRequest.java
  src/main/java/com/mfc/coordinating/confirms/dto/request/ConfirmsUpdateRequest.java
  src/main/java/com/mfc/coordinating/confirms/dto/response/ConfirmsResponse.java
  src/main/java/com/mfc/coordinating/confirms/infrastructure/ConfirmsRepository.java
  src/main/java/com/mfc/coordinating/confirms/presentation/ConfirmsController.java
Labels: 💫 feature, 🌓Backend
