Repository personull-mfc/mfc-coordinating, pull requests merged in 2024-06, with the labels that each got.

#19 refactor: 코디네이팅 레포지토리 리팩토링
  build.gradle
  src/main/java/com/mfc/coordinating/confirms/application/ConfirmsService.java
  src/main/java/com/mfc/coordinating/confirms/application/ConfirmsServiceImpl.java
  src/main/java/com/mfc/coordinating/confirms/dto/request/ConfirmsUpdateRequest.java
  src/main/java/com/mfc/coordinating/confirms/infrastructure/ConfirmsRepository.java
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesServiceImpl.java
  src/main/java/com/mfc/coordinating/coordinates/domain/Coordinates.java
  src/main/java/com/mfc/coordinating/coordinates/dto/request/CoordinatesRequest.java
  src/main/java/com/mfc/coordinating/coordinates/dto/response/CoordinatesResponse.java
  src/main/java/com/mfc/coordinating/coordinates/infrastructure/CoordinatesImageRepository.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsService.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/domain/Brand.java
  src/main/java/com/mfc/coordinating/requests/domain/Category.java
  src/main/java/com/mfc/coordinating/requests/domain/MyImage.java
  src/main/java/com/mfc/coordinating/requests/domain/ReferenceImage.java
  src/main/java/com/mfc/coordinating/requests/domain/RequestHistory.java
  src/main/java/com/mfc/coordinating/requests/domain/Requests.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsCreateReqDto.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsUpdateReqDto.java
  src/main/java/com/mfc/coordinating/requests/dto/res/RequestsDetailResDto.java
  src/main/java/com/mfc/coordinating/requests/dto/res/RequestsListResDto.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/BrandRepository.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/CategoryRepository.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/MyImageRepository.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/ReferenceImageRepository.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestHistoryRepository.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestsRepository.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
  src/main/java/com/mfc/coordinating/requests/vo/req/RequestsCreateReqVo.java
  src/main/java/com/mfc/coordinating/requests/vo/req/RequestsUpdateReqVo.java
  src/main/java/com/mfc/coordinating/requests/vo/res/RequestsDetailResVo.java
  src/main/java/com/mfc/coordinating/requests/vo/res/RequestsHistoryListVo.java
  src/main/java/com/mfc/coordinating/trade/application/TradeService.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/domain/Trade.java
  src/main/java/com/mfc/coordinating/trade/dto/request/TradeRequest.java
  src/main/java/com/mfc/coordinating/trade/dto/request/TradeUpdateRequest.java
  src/main/java/com/mfc/coordinating/trade/dto/response/TradeResponse.java
  src/main/java/com/mfc/coordinating/trade/enums/TradeStatus.java
  src/main/java/com/mfc/coordinating/trade/infrastructure/TradeRepository.java
  src/main/java/com/mfc/coordinating/trade/presentation/TradeController.java
Labels: ♻️ refactor, 🌓Backend

#21 feat: 거래 생성, 확정 시 카프카로 결제서비스에 전달
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/trade/application/TradeEventProducer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
Labels: 💫 feature, 🌓Backend

#23 refactor: RequestHistory 몽고 디비 변경 및 컬럼 추가
  build.gradle
  src/main/java/com/mfc/coordinating/coordinates/domain/Coordinates.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsEventProducer.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/domain/RequestHistory.java
  src/main/java/com/mfc/coordinating/requests/domain/Requests.java
  src/main/java/com/mfc/coordinating/requests/dto/res/RequestsListResDto.java
  src/main/java/com/mfc/coordinating/requests/vo/res/RequestsHistoryListVo.java
Labels: ♻️ refactor, 🌓Backend

#25 jpa-mongodb repository 관련 버그 수정
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestHistoryRepository.java
Labels: 🐛bug, 🌓Backend

#28 feat: 코디 및 요청서 기능 추가 및 리팩토링
  src/main/java/com/mfc/coordinating/common/response/BaseResponseStatus.java
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesService.java
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesServiceImpl.java
  src/main/java/com/mfc/coordinating/coordinates/domain/Coordinates.java
  src/main/java/com/mfc/coordinating/coordinates/dto/request/CoordinatesRequest.java
  src/main/java/com/mfc/coordinating/coordinates/dto/response/CoordinatesResponse.java
  src/main/java/com/mfc/coordinating/coordinates/enums/CoordinateCategory.java
  src/main/java/com/mfc/coordinating/coordinates/presentation/CoordinatesController.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsEventProducer.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsService.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/domain/Category.java
  src/main/java/com/mfc/coordinating/requests/domain/RequestHistory.java
  src/main/java/com/mfc/coordinating/requests/dto/res/MyRequestListResponse.java
  src/main/java/com/mfc/coordinating/requests/dto/res/RequestsListResDto.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestHistoryRepository.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestsRepository.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
  src/main/java/com/mfc/coordinating/trade/application/TradeExpiredEventConsumer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeService.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/domain/Trade.java
  src/main/java/com/mfc/coordinating/trade/dto/request/TradeRequest.java
  src/main/java/com/mfc/coordinating/trade/dto/response/TradeResponse.java
  src/main/java/com/mfc/coordinating/trade/enums/TradeStatus.java
  src/main/java/com/mfc/coordinating/trade/infrastructure/TradeRepository.java
Labels: 💫 feature, ♻️ refactor, 🌓Backend

#34 fix: 요청서 생성시 카프카에서 feign client 사용하는 방식으로 변경 및 결제 시 요청상태 변경 로직 추가
  build.gradle
  src/main/java/com/mfc/coordinating/CoordinatingApplication.java
  src/main/java/com/mfc/coordinating/common/client/AuthClient.java
  src/main/java/com/mfc/coordinating/common/client/AuthInfoResponse.java
  src/main/java/com/mfc/coordinating/common/client/MemberClient.java
  src/main/java/com/mfc/coordinating/common/client/MemberInfoResponse.java
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/requests/application/RequestEventConsumer.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsEventConsumer.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsEventProducer.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsService.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/domain/Requests.java
  src/main/java/com/mfc/coordinating/requests/dto/kafka/AuthInfoResponseDto.java
  src/main/java/com/mfc/coordinating/requests/dto/kafka/CashDeductionRequestDto.java
  src/main/java/com/mfc/coordinating/requests/dto/kafka/PaymentCompletedEvent.java
  src/main/java/com/mfc/coordinating/requests/dto/kafka/RequestsUserInfoDto.java
  src/main/java/com/mfc/coordinating/requests/dto/req/AuthInfoRequestDto.java
  src/main/java/com/mfc/coordinating/requests/dto/req/ConfirmProposalRequest.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsCreateReqDto.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsUpdateReqDto.java
  src/main/java/com/mfc/coordinating/requests/dto/req/UserInfoRequestDto.java
  src/main/java/com/mfc/coordinating/requests/dto/res/RequestsDetailResDto.java
  src/main/java/com/mfc/coordinating/requests/dto/res/RequestsListResDto.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
Labels: 🐛bug, 🌓Backend

#36 파트너 요청 수락 시 채팅방 생성 메세지 전송
  src/main/java/com/mfc/coordinating/common/client/AuthClient.java
  src/main/java/com/mfc/coordinating/common/client/MemberClient.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsEventProducer.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/dto/kafka/CreateChatRoomDto.java
Labels: 💫 feature, ♻️ refactor, 🌓Backend

#37 fix: 값 받을 때 기본검증 및 카프카 설정 변경
  build.gradle
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/requests/application/RequestEventConsumer.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/dto/req/ConfirmProposalRequest.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsCreateReqDto.java
  src/main/java/com/mfc/coordinating/requests/dto/req/RequestsUpdateReqDto.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
  src/main/java/com/mfc/coordinating/trade/application/TradeEventProducer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeExpiredEventConsumer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/domain/Trade.java
  src/main/java/com/mfc/coordinating/trade/dto/kafka/TradeSettledEventDto.java
  src/main/java/com/mfc/coordinating/trade/dto/request/TradeRequest.java
  src/main/java/com/mfc/coordinating/trade/dto/response/TradeResponse.java
  src/main/java/com/mfc/coordinating/trade/infrastructure/TradeRepository.java
  src/main/java/com/mfc/coordinating/trade/presentation/TradeController.java
Labels: ♻️ refactor, 🌓Backend

#38 빌드 에러 수정
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
Labels: 🐛bug, 🌓Backend

#40 feat: 리뷰 작성 시 집계 위해 카프카 토픽 발행 로직 추가 및 코디 요청 확정 시 데드라인도 같이 보내게 수정
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsService.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
  src/main/java/com/mfc/coordinating/reviews/application/ReviewEventProducer.java
  src/main/java/com/mfc/coordinating/reviews/application/ReviewsService.java
  src/main/java/com/mfc/coordinating/reviews/application/ReviewsServiceImpl.java
  src/main/java/com/mfc/coordinating/reviews/dto/kafka/ReviewSummaryDto.java
  src/main/java/com/mfc/coordinating/reviews/dto/request/ReviewsRequest.java
  src/main/java/com/mfc/coordinating/reviews/dto/response/ReviewsResponse.java
  src/main/java/com/mfc/coordinating/reviews/entity/Reviews.java
  src/main/java/com/mfc/coordinating/reviews/infrastructure/ReviewsRepository.java
  src/main/java/com/mfc/coordinating/reviews/presentation/ReviewsController.java
  src/main/java/com/mfc/coordinating/trade/application/TradeEventProducer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/dto/kafka/TradeSettledEventDto.java
Labels: ⚙️ chore, 💫 feature, 🌓Backend

#42 fix: 코디네이팅 requestId로 변경, 거래 not_paid 추가, my-request response 변경
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesServiceImpl.java
  src/main/java/com/mfc/coordinating/coordinates/domain/Coordinates.java
  src/main/java/com/mfc/coordinating/coordinates/dto/request/CoordinatesRequest.java
  src/main/java/com/mfc/coordinating/coordinates/dto/response/CoordinatesResponse.java
  src/main/java/com/mfc/coordinating/requests/dto/res/MyRequestListResponse.java
  src/main/java/com/mfc/coordinating/requests/mapper/RequestMapper.java
  src/main/java/com/mfc/coordinating/trade/application/TradeEventProducer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeExpiredEventConsumer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/domain/Trade.java
  src/main/java/com/mfc/coordinating/trade/enums/TradeStatus.java
Labels: 🐛bug, 🌓Backend

#44 fix: 삭제, 수정은 coordinateId로 하게 변경 및 조회시 리스트로 반환
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesService.java
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesServiceImpl.java
  src/main/java/com/mfc/coordinating/coordinates/infrastructure/CoordinatesRepository.java
  src/main/java/com/mfc/coordinating/coordinates/presentation/CoordinatesController.java
Labels: 🐛bug, 🌓Backend

#46 fix: 코디네이팅 엔티티에 partnerId 추가 , 코디 제출 시 request 상태 변경, 기타 리팩토링 진행
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesService.java
  src/main/java/com/mfc/coordinating/coordinates/application/CoordinatesServiceImpl.java
  src/main/java/com/mfc/coordinating/coordinates/domain/Coordinates.java
  src/main/java/com/mfc/coordinating/coordinates/dto/kafka/CoordinatesSubmittedEventDto.java
  src/main/java/com/mfc/coordinating/coordinates/presentation/CoordinatesController.java
  src/main/java/com/mfc/coordinating/requests/application/RequestEventConsumer.java
  src/main/java/com/mfc/coordinating/requests/enums/RequestsStates.java
  src/main/java/com/mfc/coordinating/reviews/application/ReviewsService.java
  src/main/java/com/mfc/coordinating/reviews/application/ReviewsServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/application/TradeService.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/presentation/TradeController.java
Labels: ⚙️ chore, ♻️ refactor, 🌓Backend

#48 fix: 거래 최종 완료시 request에서 trade 토픽 구독하여 상태 변경
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/requests/application/RequestEventConsumer.java
  src/main/java/com/mfc/coordinating/requests/enums/RequestsStates.java
  src/main/java/com/mfc/coordinating/trade/application/TradeEventProducer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/dto/kafka/TradeSettledEventDto.java
Labels: 💫 feature, 🌓Backend

#50 fix: 거래 최종 완료시 request에서 trade 토픽 구독하여 상태 변경
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/requests/application/RequestEventConsumer.java
  src/main/java/com/mfc/coordinating/requests/domain/Requests.java
  src/main/java/com/mfc/coordinating/requests/enums/RequestsStates.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
  src/main/java/com/mfc/coordinating/trade/application/TradeEventProducer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/dto/kafka/TradeDueDateEventDto.java
Labels: 💫 feature, 🌓Backend

#52 파트너 프로필 집계 관련 로직 구현
  src/main/java/com/mfc/coordinating/requests/application/RequestEventConsumer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeEventProducer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeServiceImpl.java
  src/main/java/com/mfc/coordinating/trade/dto/kafka/PartnerSummaryDto.java
Labels: 💫 feature, 🌓Backend

#55 feat: 요청서 목록 조회 시 요청 응답별로 필터링 적용
  src/main/java/com/mfc/coordinating/requests/application/RequestsService.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestsRepository.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
Labels: 💫 feature, 🌓Backend

#58 fix: 몽고 디비 에러 수정
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestsRepository.java
Labels: 🐛bug, 🌓Backend

#59 fix: eleMatch로 수정
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestsRepository.java
Labels: 🐛bug, 🌓Backend

#62 feat: 요청서 상태별 필터링 적용 및 파트너 상태 가져오는 API 구현
  src/main/java/com/mfc/coordinating/requests/application/RequestsService.java
  src/main/java/com/mfc/coordinating/requests/application/RequestsServiceImpl.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/CustomRequestsRepository.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/CustomRequestsRepositoryImpl.java
  src/main/java/com/mfc/coordinating/requests/infrastructure/RequestsRepository.java
  src/main/java/com/mfc/coordinating/requests/presentation/RequestsController.java
Labels: 🐛bug, 💫 feature, 🌓Backend

#63 fix: 요청서 반환시 유저정보 반환 못하는 문제 수정
  src/main/java/com/mfc/coordinating/requests/infrastructure/CustomRequestsRepositoryImpl.java
Labels: 🐛bug, 🌓Backend

#64 fix: 요청서 상태 변경 오류 수정
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/requests/application/RequestEventConsumer.java
Labels: 🐛bug, 🌓Backend

#65 fix: 요청서 상태 변경 오류 수정
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
Labels: 🐛bug, 🌓Backend

#66 fix: 요청서 상태 변경 오류 수정
  src/main/java/com/mfc/coordinating/config/KafkaConfig.java
  src/main/java/com/mfc/coordinating/requests/application/RequestEventConsumer.java
  src/main/java/com/mfc/coordinating/trade/application/TradeExpiredEventConsumer.java
Labels: 🐛bug, 🌓Backend
